# docker-compose.yml
services:
  db:
    image: postgres:14
    container_name: library_db
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U library_user -d library_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: library_api
    environment:
      DATABASE_URL: "postgresql://library_user:library_password@db:5432/library_db"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
